### ISSUE TITLE
Each event must have a detail page

### ISSUE THREAD

**Issue by jeffmcq1616** [spring-giant/mgt656-spring-2015-project#10]

**Comment by jeffmcq1616** [comment]
Note: When I run the test, it's not passing for the detail pages having a title, date, location, etc. When I look at the specifics, it says that Event 2 doesn't have a title. Which is weird, because it definitely does! Can anyone look at the code on the event-details page and see if I'm missing something??

I completed this story in about 2.25 hours, but I'm not quite sure that I used the span tags correctly. We should probably check over the code to make sure it's ok!

--As an attendee, I can visit the event detail page to see relevant information about the event:
    -I can view the event title.
        Grading note: It should be in a h1 element with the id title.
    -I can view the event date.
        Grading note: It should be in a span tag with the id date.
    -I can view the event location.
        Grading note: It should be in a span tag with the id location.
    -I can see the event's image on the page.
        Grading note: It has the id image.
    -I can see an unordered list of the event's attendees.
        Grading note: It has the id attendees.

Point/Time Estimations:

-Determining how to create an Event Page:8 pts/3 hrs (Completed in 1.5 hrs)
-Writing the code for title, date, location, image: 3 pts/1 hr (Completed in 0.5 hrs)
-Writing the code for the unordered list of attendees: 3 pts/1 hr (Completed in 0.25 hrs)

**Comment by meghaghildyal** [comment]
Jeff, I am not sure if I have the time to look at this now because I am working on my own story. However, the TAs are highly responsive on e-mail. if you send them your Q with screenshots, they would reply v soon. If need be, they are willing to share cloud9 screens and work on the problem with you as well..

**Comment by meghaghildyal** [comment]
was going over this.. so you've not pushed this to master yet? Unless the event page is created it seems rsvp will not work either...

**Comment by meghaghildyal** [comment]
can you e-mail me the code you have written for the event detail page?or paste it here

**Comment by meghaghildyal** [comment]
Tried doing it-getting similar error, "no date in event 2". Wrote to the TA Mike Wu. I am stuck with the RSVP as well. I think it is related to your test.

**Comment by meghaghildyal** [comment]
Resolved. Took me a very long time. Jeff, I recommend you inform the TA's / seek help from someone who knows coding as soon as you encounter such a problem, so you get enough time for the query to be resolved.
It took me quite a long time to write the entire code and then troubleshoot.
(you were missing h1 id="title", span id="date" etc.)

**Comment by jeffmcq1616** [comment]
Oh I see. Gotcha.

On Nov 14, 2015, at 11:18 AM, Megha G <notifications@github.com<mailto:notifications@github.com>> wrote:

Resolved. Took me a very long time. Jeff, I recommend you inform the TA's / seek help from someone who knows coding, so you get enough time for the query to be resolved.
It took me quite a long time to write the entire code and then troubleshoot.
{% extends "layout.html" %}

{% block mainContent %}

{{event.title}}

[cid:%7B%7Bevent.image%7D%7D]<%7B%7Bevent.image%7D%7D>

Date and Time: {{event.date}}

Location: {{event.location}}

Attendees:

{% for person in event.attending %}
-   {{person}}
  {% endfor %} RSVP through your Yale e-mail:
  {% if errors %}
  {% for error in errors %}
  -   {{error}}
    {% endfor %}

{% endif %}

{% endblock %}

(you were missing h1 id="title", span id="date" etc.)
