### ISSUE TITLE
Create an "About Us" page

### ISSUE THREAD

**Issue by jeffmcq1616** [spring-giant/mgt656-spring-2015-project#11]
As a user, I can visit the url at /about and see information about your company including:
your names, each in a span tag with id attribute set to your class nickname with a -name suffix, e.g. "fast-lion-name".
a headshot of you each in an img tag with id attribute set to your class nickname with a -headshot suffix, e.g. "fast-lion-headshot". This does not have to actually be a picture of you.

**Comment by peapumpkin** [comment]
Ask for headshots from the team

**Comment by peapumpkin** [comment]
my nickname is enthusiastic-opossum

**Comment by jeffmcq1616** [comment]
my nickname is helpful-emu
