### ISSUE TITLE
As a user, I can visit your API at /api/events and retrieve an object with key events containing all events in JSON format

### ISSUE THREAD

**Issue by jeffmcq1616** [spring-giant/mgt656-spring-2015-project#13]
As a user, I can visit your API at /api/events and retrieve an object with key events containing all events in JSON format. For example, the response may look akin to the following:
{
  events: [
    {
      id: 0,
      title: "...",
      location: "...",
      ...
    },
    {
      id: 1,
      title: "...",
      location: "...",
      ...
    },
  ]
}
I can search for events by submitting a GET request to a URL like /api/events?search=beach and only receive back events that have ‘beach’ in the event title.

**Comment by meghaghildyal** [comment]
Jared, look at Kyle's video. This shouldn't take you more than half hour to do

**Comment by meghaghildyal** [comment]
Jared, look at Kyle's video. This will take you no more than half hour to complete
