### ISSUE TITLE
Develop a search function that searches by keywords in the title

### ISSUE THREAD

**Issue by jeffmcq1616** [spring-giant/mgt656-spring-2015-project#14]
I can search for events by submitting a GET request to a URL like /api/events?search=beach and only receive back events that have ‘beach’ in the event title.

**Comment by jmaclane** [comment]
As stated in the project....We can search by "keyword in the title" from the url 
EX: api/events?search=BBQ
Test passes

**Comment by meghaghildyal** [comment]
This is just searching API and is not an actual search button on the homepage.. While the test passes for this, shouldn't we eventually build a search function that an actual user can use? Why not add that as a user story as well?
