### ISSUE TITLE
Design new team logo & place it at the top of all pages

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#21]

**Comment by meghaghildyal** [comment]
Hey Jared, It seems more than one team already has the logo with a calendar on it. Could we have a prettier one, something like the one we have right now?-Megha

**Comment by jmaclane** [comment]
Some questions remain on the name and direction. Will bring up at the next meeting.

**Comment by peapumpkin** [comment]
I suggest changing the font. I like the name Evently! The calendar is fine with me, though if it's too similar to other teams that is a concern.

**Comment by jmaclane** [comment]
New logo is visible on all pages. Font modification and upload time 5 mins. If someone has the font (futura) available and would like to modify the logo...then I will update the  file again.
