### ISSUE TITLE
Create event form: When submitted, the event creation form should be  validated

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#28]
When submitted, the form should be validated:
The image URL must begin with ‘http://’ or ‘https://’ and end with ‘.gif’ or ‘.png’.
The title must be less than 50 characters
The location must be less than 50 characters
The year must be 2015 or 2016
The month must be between 0 to 11, inclusive
The hour must be 0-23
The minute must be 0 or 30

**Comment by peapumpkin** [comment]
Created addEventValidation branch. Worked for 50 minutes. Need to use https://github.com/chriso/validator.js. Now 12 tests passing, but need to do 4 more for this subtask. 
    7) should display errors to the user when the image is not a gif or png
     8) should display errors to the user when the image is not a URL
     9) should display errors to the user when the location is too long
     10) should display errors to the user when the location is empty

**Comment by meghaghildyal** [comment]
changed it to 1 hour (=3 points)

**Comment by peapumpkin** [comment]
All 16 tests passing for this subtask. Pull request submitted. ~2.25 hours total

**Comment by meghaghildyal** [comment]
Can't view pull request- sent screenshots via mail.

**Comment by peapumpkin** [comment]
You already merged it: https://github.com/spring-giant/mgt656-spring-2015-project/pull/41
