### ISSUE TITLE
Create event form: Users can submit new event form

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#31]
I can click a input element to submit the event. This element should have id="submit" and type="submit".

**Comment by peapumpkin** [comment]
Done. This was quick! Now onto make the form options selectable, that will take longer to figure out. Doing this task and making selectable options on same branch.

**Comment by peapumpkin** [comment]
Submitted pull request.

**Comment by meghaghildyal** [comment]
close this?
