### ISSUE TITLE
Create Event Form: When new event form is not valid, take users back to form and show errors

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#32]
If the form was not valid, I am taken back the form and the errors are shown on the form.

The errors should be enumerated in a ul element with class="form-errors"
That ul element should have li elements for each error. For example, your errors may look like this
  <ul class="form-errors">
    <li>Error, the title must be between 0 and 50 characters</li>
  </ul>

**Comment by meghaghildyal** [comment]
I suppose this is under progress.. Are we putting this in sprint-5 report?

**Comment by jeffmcq1616** [comment]
Completed! Lea made some changes to the app.js code to make this work properly!
