### ISSUE TITLE
Create Event Form: When event creation form is valid, redirect to detail page for new event

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#33]
If the submitted form is valid, I am redirected to the detail page for that new event. This redirect is accomplished using a "302" HTTP response. (See the documentation for the Express.js response redirect method)
  Test 11) should redirect the user to the event detail page if the form is valid

**Comment by meghaghildyal** [comment]
Wow Lea, you're a pro at coding now! :)

**Comment by jeffmcq1616** [comment]
This might not be too bad. For the code in the controller events.js (lines 96 to 109):

 if (contextData.errors.length === 0) {
    var newEvent = {
      title: request.body.title,
      location: request.body.location,
      image: request.body.image,
      date: new Date(),
      attending: []
    };
    events.all.push(newEvent);
    response.redirect('/events');
  }else{
    response.render('create-event.html', contextData);
  }
}

I think all we need to do is change the response.redirect('/events') to response.redirect('events/:id'). I'm not exactly sure if this is the correct syntax--I'm not sure if ":id" will take the user to the detail page for the new event--but it's something like this.

**Comment by meghaghildyal** [comment]
So right now if the details for new event are entered correctly, we just come back to the same page to create another new event. The test for form for creating new event is passing. The event we just created is not visible under 'browse events'  and is basically 'lost' right now after creation . Am i correct? Just want to confirm...

**Comment by jeffmcq1616** [comment]
Completed on 12/2. Took about an hour. All tests are now passing!!!
