### ISSUE TITLE
Better formatting: Make logo link to homepage

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#34]

**Comment by jmaclane** [comment]
Homepage is accessible from all pages by clicking logo. Logo is linked to (http://spring-giant-jmaclane.c9.io/) as a placeholder for our final URL mainpage or homepage.

**Comment by jmaclane** [comment]
Note: total time 10mins, including formatting and research

**Comment by meghaghildyal** [comment]
Done. replaced jared's previous link with <a href="/"> for redirection to homepage. 3 min
