### ISSUE TITLE
Create sprint-report in html and host it on html

### ISSUE THREAD

**Issue by meghaghildyal** [spring-giant/mgt656-spring-2015-project#45]
http://spring-giant1-meghaghildyal.c9.io/sprint-report4

**Comment by meghaghildyal** [comment]
We have lost 10 points int he past three sprint reports for the following-
It could be written in HTML (0/5)
It could be hosted online as HTML (0/5)

**Comment by meghaghildyal** [comment]
Jeff can you send me the sprint-4 report word doc by Sunday night 9 pm so I can put it on html, thanks

**Comment by meghaghildyal** [comment]
Every time we create a new sprint report, we create a new javascript file in Controllers and new html file in views, by the sprintreport(number), then we make changes in app.js

**Comment by jeffmcq1616** [comment]
I can get it to you by 9, no prob. Are you sure it's worth the added effort? I know it's written as a deduction in points, but it was presented to the class as more of a bonus. We actually discussed this during our Tuesday meeting (I forgot to put it in the notes!) and didn't think we had the bandwidth to do it. But definitely go for it if you'd like. Let me know if it works out so I know whether or not to submit the google doc.

**Comment by meghaghildyal** [comment]
We are definitely being graded for it. Once set up (I set it up today and it took me two hours to figure out), the time for doing it again is just half hour. So doesn't make sense to lose points for free.
I'll train everyone on the three steps outlined in my previous comment. Hence on, it will only take 30-40 min to populate the html. I'm happy to take this on so long as someone else does writing of the report in doc format.
