### ISSUE TITLE
Create Event Form: Form should have selectable options.

### ISSUE THREAD

**Issue by meghaghildyal** [spring-giant/mgt656-spring-2015-project#46]
The year, month, day, hour, and minute form elements should be select elements.
The minute should only have 0, and 30 as selections. (At the hour and half hour).
The hour select should be in 24-hour time format: 0-23 are selectable.
The month select should have integer value attributes, numbered 0-11, and refer to months by their names: January, February, etc.
You should only be able to schedule events in 2015 and 2016

**Comment by meghaghildyal** [comment]
4th test in 'mocha -g detail'

**Comment by peapumpkin** [comment]
This is the same as #33...

**Comment by peapumpkin** [comment]
I finished this last night, took me about 3 hours, but one of the tests is not passing "should have the appropriate options for select elements". So I didn't submit it to be merged to master yet. I spent a while trying but I can't figure it out. I looked at the test itself and don't understand why it's not passing. Megha or Jeff, could you try to take a look at it? And I'll ask the TAs.

**Comment by peapumpkin** [comment]
This is the test not passing: 
it('should have the appropriate options for select elements', function () {
      var requiredFieldValues = {
        'year' : [2015, 2016],
        'month' : _.range(12),
        'hour' : _.range(24),
        'minute' : [0, 30]
      };

**Comment by peapumpkin** [comment]
Ah nevermind I figured it out!! Submitting for merge now.

**Comment by meghaghildyal** [comment]
Merged and pushed to Heroku

**Comment by meghaghildyal** [comment]
can this be closed now?
