### ISSUE TITLE
Make donation link

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#48]
Make donation link with class=”donation”
See how traffic breaks down across different segments and how they flow through your "funnel" from landing to donation
Much of your traffic comes from referals from specific school sites: SOM, law,  etc. Some of the visitors are more likely to click through to an event detail page (e.g. /events/2) than others. Once there, some will donate to support an event if you have a donation link.

**Comment by meghaghildyal** [comment]
Donation button below Submit button on event detail page. Leads to blank donation page
