### ISSUE TITLE
Style/Format Create Events Page & Individual Event Pages

### ISSUE THREAD

**Issue by peapumpkin** [spring-giant/mgt656-spring-2015-project#52]

**Comment by meghaghildyal** [comment]
Can everyone please give their profile write up for the about us page. 2-3 lines are sufficient.

**Comment by meghaghildyal** [comment]
Styled create event page boxes-half hour. Defined class called "textbox" in css:
.textbox {
  padding: 5px;
  border: solid 1px #fff;
  box-shadow: inset 1px 1px 2px 0 #707070;
  transition: box-shadow 0.3s;
}

**Comment by meghaghildyal** [comment]
Gave bootstrap styling to submit and donate buttons-40 minutes

**Comment by meghaghildyal** [comment]
styled font,changed background, changed positioning of buttons etc. on event detail page- 1 hour

**Comment by meghaghildyal** [comment]
Tried several backgrounds, themes, fonts and colors for create event and individual event pages-3 hours

**Comment by peapumpkin** [comment]
Thanks for working on all of this. I really think we should have solid backgrounds for pages, not images. It's too busy looking.

**Comment by meghaghildyal** [comment]
Hi Lea, I spent 4 hours last night, till 3 am, just looking for the right background- the correct size, something that doesn't hide the header and footer, somewhat goes with the 'theme' of the rest of the pages and fun events on the website. It will be great if you can e-mail me urls of some background images that you want me to put in any of the pages. In fact, suggestions (in the form of URLs) welcome from Jeff and Jared as well. I really feel that me spending anymore time on the right background image will be highly counterproductive as I have run out of web resources.. thanks!

**Comment by meghaghildyal** [comment]
Here are URLs of some images that 'should' fit our page:

http://revelwallpapers.net/d/77334F64716F764C7664664F6870686C7A4878327A4C33423371647A69673D3D/mood_flowers_flowers_petals_white_wood_background_wallpaper_widescreen_fullscreen_widescreen.jpg 

The size of this may be ok but it is not a free image- another problem which hampered progress quite a bit yesterday:

http://thumbs.dreamstime.com/z/butterflies-free-flight-digital-graphic-illustration-against-oil-paint-textured-background-42718436.jpg

**Comment by meghaghildyal** [comment]
Please update your bio in about.html
