### ISSUE TITLE
Improve Usability/Formatting: Add better formatting to 'create a new event' method on homepage

### ISSUE THREAD

**Issue by jeffmcq1616** [spring-giant/mgt656-spring-2015-project#9]

**Comment by jmaclane** [comment]
added new 'Create Event' button. Included and img with the href and moved the code to the top of the body (container).

**Comment by jmaclane** [comment]
gulp is crashing. Changes have been made, added via git-add. Not able to commit branch. Waiting for TA assistance.

**Comment by jmaclane** [comment]
resolved issue: changes are live on site
